### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by jpfleblanc** [aeantipov/opendf#1]
Appears to be growing memory usage in DF self consistency loop.

Typical memory usage is small, so has gone unnoticed.  Also not picked up for cases that converge quickly.

Currently using large vertex files, 30+MB, after 100+ iterations with small mixing you're looking at 3GB or more of memory usage.

**Comment by aeantipov** [comment]
That seemed to be the gftools bug, fixed it with 991f03e931ae771182af956a9e35dca63f5d030b there. Update both opendf and gftools. Tell me if it works, thanks!
