### ISSUE TITLE
problems with lattice_test.cpp

### ISSUE THREAD

**Issue by egull** [aeantipov/opendf#2]
lattice test fails to compile

this seems to be an incompatibility with C++-11 and icc 16. Here is a list of errors and warnings.

/home/egull/opendf/test/lattice_test.cpp(24): error: no instance of overloaded function "open_df::cubic_traits<D>::dispersion [with D=1UL]" matches the argument list
            argument types are: (bz_point)
            object type is: open_df::cubic_traits<1UL>
          double disp_val = lattice.dispersion(orig);
                                    ^
          detected during instantiation of "void test_symmetry(LatticeT, int) [with LatticeT=open_df::cubic_traits<1UL>]" at line 38

/home/egull/opendf/test/lattice_test.cpp(26): error: no instance of overloaded function "open_df::cubic_traits<D>::dispersion [with D=1UL]" matches the argument list
            argument types are: (bz_point)
            object type is: open_df::cubic_traits<1UL>
              ASSERT_NEAR(disp_val, lattice.dispersion(p), 1e-12);
              ^
          detected during instantiation of "void test_symmetry(LatticeT, int) [with LatticeT=open_df::cubic_traits<1UL>]" at line 38

/home/egull/opendf/test/lattice_test.cpp(24): error: no instance of overloaded function "open_df::cubic_traits<D>::dispersion [with D=2UL]" matches the argument list
            argument types are: (bz_point)
            object type is: open_df::cubic_traits<2UL>
          double disp_val = lattice.dispersion(orig);
                                    ^
          detected during instantiation of "void test_symmetry(LatticeT, int) [with LatticeT=open_df::cubic_traits<2UL>]" at line 39

/home/egull/opendf/test/lattice_test.cpp(26): error: no instance of overloaded function "open_df::cubic_traits<D>::dispersion [with D=2UL]" matches the argument list
            argument types are: (bz_point)
            object type is: open_df::cubic_traits<2UL>
              ASSERT_NEAR(disp_val, lattice.dispersion(p), 1e-12);
              ^
          detected during instantiation of "void test_symmetry(LatticeT, int) [with LatticeT=open_df::cubic_traits<2UL>]" at line 39

/home/egull/opendf/test/lattice_test.cpp(24): error: no instance of overloaded function "open_df::cubic_traits<D>::dispersion [with D=3UL]" matches the argument list
            argument types are: (bz_point)
            object type is: open_df::cubic_traits<3UL>
          double disp_val = lattice.dispersion(orig);
                                    ^
          detected during instantiation of "void test_symmetry(LatticeT, int) [with LatticeT=open_df::cubic_traits<3UL>]" at line 40

/home/egull/opendf/test/lattice_test.cpp(26): error: no instance of overloaded function "open_df::cubic_traits<D>::dispersion [with D=3UL]" matches the argument list
            argument types are: (bz_point)
            object type is: open_df::cubic_traits<3UL>
              ASSERT_NEAR(disp_val, lattice.dispersion(p), 1e-12);
              ^
          detected during instantiation of "void test_symmetry(LatticeT, int) [with LatticeT=open_df::cubic_traits<3UL>]" at line 40

/home/egull/opendf/test/lattice_test.cpp(24): error: no instance of overloaded function "open_df::cubic_traits<D>::dispersion [with D=4UL]" matches the argument list
            argument types are: (bz_point)
            object type is: open_df::cubic_traits<4UL>
          double disp_val = lattice.dispersion(orig);
                                    ^
          detected during instantiation of "void test_symmetry(LatticeT, int) [with LatticeT=open_df::cubic_traits<4UL>]" at line 41

/home/egull/opendf/test/lattice_test.cpp(26): error: no instance of overloaded function "open_df::cubic_traits<D>::dispersion [with D=4UL]" matches the argument list
            argument types are: (bz_point)
            object type is: open_df::cubic_traits<4UL>
              ASSERT_NEAR(disp_val, lattice.dispersion(p), 1e-12);
              ^
          detected during instantiation of "void test_symmetry(LatticeT, int) [with LatticeT=open_df::cubic_traits<4UL>]" at line 41

/home/egull/opendf/test/lattice_test.cpp(24): error: no instance of overloaded function "open_df::triangular_traits::dispersion" matches the argument list
            argument types are: (bz_point)
            object type is: open_df::triangular_traits
          double disp_val = lattice.dispersion(orig);
                                    ^
          detected during instantiation of "void test_symmetry(LatticeT, int) [with LatticeT=open_df::triangular_traits]" at line 42

/home/egull/opendf/test/lattice_test.cpp(26): error: no instance of overloaded function "open_df::triangular_traits::dispersion" matches the argument list
            argument types are: (bz_point)
            object type is: open_df::triangular_traits
              ASSERT_NEAR(disp_val, lattice.dispersion(p), 1e-12);
              ^
          detected during instantiation of "void test_symmetry(LatticeT, int) [with LatticeT=open_df::triangular_traits]" at line 42

/home/egull/opendf/test/lattice_test.cpp(24): error: no instance of overloaded function "open_df::square_nnn_traits::dispersion" matches the argument list
            argument types are: (bz_point)
            object type is: open_df::square_nnn_traits
          double disp_val = lattice.dispersion(orig);
                                    ^
          detected during instantiation of "void test_symmetry(LatticeT, int) [with LatticeT=open_df::square_nnn_traits]" at line 44

/home/egull/opendf/test/lattice_test.cpp(26): error: no instance of overloaded function "open_df::square_nnn_traits::dispersion" matches the argument list
            argument types are: (bz_point)
            object type is: open_df::square_nnn_traits
              ASSERT_NEAR(disp_val, lattice.dispersion(p), 1e-12);
              ^
          detected during instantiation of "void test_symmetry(LatticeT, int) [with LatticeT=open_df::square_nnn_traits]" at line 44

compilation aborted for /home/egull/opendf/test/lattice_test.cpp (code 2)
make[2]: *** [test/CMakeFiles/lattice_test.dir/lattice_test.cpp.o] Error 2
make[1]: *** [test/CMakeFiles/lattice_test.dir/all] Error 2
make: *** [all] Error 2

**Comment by aeantipov** [comment]
Emanuel, what does `icpc -v` give?

**Comment by egull** [comment]
[egull@flux-login2 ~]$ icpc -v
icpc version 16.0.3 (gcc version 4.8.5 compatibility)

**Comment by aeantipov** [comment]
Looking into this. Yeah, it seems to be a problem with intel and automatic conversion between std::array and std::tuple. They should be convertible, but for some compilers it is not. I remember having a workaround for this before in gftools, I'll see if it can be used here. It is not very important though, the test is trivial.

**Comment by aeantipov** [comment]
Ok, fixed now with 273428dda7d67c8c07615dbec87b8c3e2afaaa6b. Please update gftools too (commit 07b6fd06d762ed87140fb008cdc4295535c1ae64). Check if that works.
