### ISSUE TITLE
Hub_DF_square_nnn Seg Fault

### ISSUE THREAD

**Issue by DalInar** [aeantipov/opendf#6]
Running into a seg fault with the hub_df_square_nnn code.  Here's a link to a zip folder that contains the qmc_output.h5, the command I'm using to run opendf, and a log of the output and error that I get.  

https://www.dropbox.com/s/z6l7ji8ni4ml7cj/run_command.zip?dl=0

Could you see if you also get a seq fault / help me figure out what I'm doing wrong?

**Comment by jpfleblanc** [comment]
log suggests crash is due to resume failure.

script has text '--resume > log' which should be '--resume 1 > log'

Regardless, code SHOULD respond that --resume needs an argument.

Cannot reproduce error.  So far checked revision from november ( 273428dda7d67c8c07615dbec87b8c3e2afaaa6b )

Will check updated version.

**Comment by jpfleblanc** [comment]
Appears to work on updated opendf - linked against ALPSCore 0.5.4

Could be change in alpscore causing issue.  Will followup.

Workaround - Install ALPSCore 0.5.4 and compile opendf linked to that, see if error vanishes.

**Comment by jpfleblanc** [comment]
works on ALPSCore jan 5th revision. checking most up to date.

**Comment by jpfleblanc** [comment]
Updated ALPSCore appears to work.

I'm not happy now that I look at the log with seeing the mention of 'pthreads'.  Probably something in alps is using mpi, and opendf was not compiled with MPI. 

Recommend installing ALPSCore with minimal options, MPI enabled, and compile opendf ALSO with mpicxx compiler.  

Example script:

export ALPSCore_DIR=/home/jpfleblanc/alps_core/ALPSCore_updated/install
CC=mpicc CXX=mpicxx cmake \
     -DCMAKE_INSTALL_PREFIX=${ALPSCore_DIR} \
     -DENABLE_MPI=ON \
     -DCMAKE_CXX_FLAGS="-DNDEBUG -DBOOST_DISABLE_ASSERTS -DALPS_GF_DEBUG" \
     -DCMAKE_BUILD_TYPE="Release" ..

and then compile opendf

CC=mpicc CXX=mpicxx  cmake -DALPSCore_DIR=/home/jpfleblanc/alps_core/ALPSCore_updated/install/share/ALPSCore/ -DCMAKE_INSTALL_PREFIX=/home/jpfleblanc/alps_core/opendf_debug/opendf/install/ -DCMAKE_BUILD_TYPE=RELEASE  ..

Please let me know if this is not the issue.

**Comment by aeantipov** [comment]
Yes. You want to use the same compiler and options for both
On Wednesday, August 9, 2017 at 09:09 James P.F. LeBlanc <notifications@github.com> wrote:

Updated ALPSCore appears to work.

I'm not happy now that I look at the log with seeing the mention of 'pthreads'. Probably something in alps is using mpi, and opendf was not compiled with MPI.

Recommend installing ALPSCore with minimal options, MPI enabled, and compile opendf ALSO with mpicxx compiler.

Example script:

export ALPSCore_DIR=/home/jpfleblanc/alps_core/ALPSCore_updated/install
CC=mpicc CXX=mpicxx cmake 
-DCMAKE_INSTALL_PREFIX=${ALPSCore_DIR} 
-DENABLE_MPI=ON 
-DCMAKE_CXX_FLAGS="-DNDEBUG -DBOOST_DISABLE_ASSERTS -DALPS_GF_DEBUG" 
-DCMAKE_BUILD_TYPE="Release" ..

and then compile opendf

CC=mpicc CXX=mpicxx cmake -DALPSCore_DIR=/home/jpfleblanc/alps_core/ALPSCore_updated/install/share/ALPSCore/ -DCMAKE_INSTALL_PREFIX=/home/jpfleblanc/alps_core/opendf_debug/opendf/install/ -DCMAKE_BUILD_TYPE=RELEASE ..

Please let me know if this is not the issue.

**Comment by DalInar** [comment]
I did compile both ALPSCore and OpenDF with the same mpicc and mpicxx.  Here's exactly what I did:

ALPSCore:
HDF5_ROOT=/u/shared/ALPSCore_stuff/software/install/ CC=mpicc CXX=mpicxx cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/u/shared/ALPSCore_stuff/install/ -DCMAKE_CXX_FLAGS="-DNDEBUG -DBOOST_DIABLE_ASSERTS -DALPS_GF_DEBUG" -DBOOST_ROOT=/u/shared/ALPSCore_stuff/software/install/ -DBoost_NO_SYSTEM_PATHS=ON -DBoost_NO_BOOST_CMAKE=ON  -DENABLE_MPI=ON ..
make
make install

OpenDF:
 HDF5_ROOT=/u/shared/ALPSCore_stuff/software/install/ CC=mpicc CXX=mpicxx cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/u/shared/ALPSCore_stuff/install/ -DALPSCore_DIR=/u/shared/ALPSCore_stuff/install/share/ALPSCore/ -DEIGEN3_INCLUDE_DIR=/u/shared/ALPSCore_stuff/software/install/include/eigen3 -DFFTW_ROOT=/u/shared/ALPSCore_stuff/software/install -DCMAKE_CXX_FLAGS="-DNDEBUG -DBOOST_DIABLE_ASSERTS -DALPS_GF_DEBUG" ..
make 
make install

Running OpenDF:
/u/shared/ALPSCore_stuff/install/bin/hub_df_square_nnn --input qmc_output.h5 --df_sc_cutoff 1.0e-8 --df_sc_iter 1200 --df_sc_mix 0.2 --fluct_diag 0 --nbosonic 32 --add_lattice_bubble 0 --mu 0.375 --tp 0.0 --resume 1 

But this gives me the same seg fault error.  Any other ideas for what to try / information I could give you guys to identify the problem?  (James, this is all on Shakuras, in case you want to try it out yourself.)

**Comment by jpfleblanc** [comment]
I forget how to login to shakuras.

I'll figure this out and try to reproduce there.

Should get to this this afternoon.

James

**Comment by DalInar** [comment]
After carefully recompiling OpenDF and all of its dependencies, the problem seems to have gone away.  As you said, I had probably just used a different compiler for one of the dependencies.
